ProjeTakip/Controllers/ProjeRaporlariController.cs
using ProjeTakip.Models.DataContext;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjeTakip.Controllers
{
    public class ProjeRaporlariController : Controller
    {
        // GET: ProjeRaporlari
       private ProjeTakipDBContext db = new ProjeTakipDBContext();
        public ActionResult TamamalanmisOncelikGruplari()
        {
            return View();
        }
        public ActionResult VisualizeSTamamlanmisDurumGruplari()
        {
            return Json(OncelikGrupTİpi(), JsonRequestBehavior.AllowGet);
        }
        public List<ClassOncelikDurumAnaliz> OncelikGrupTİpi()
        {
            ;
            List<ClassOncelikDurumAnaliz> snf = new List<ClassOncelikDurumAnaliz>();
            using (var c = new ProjeTakipDBContext())

                snf = c.PersonelProjeleris.Where(x => x.TamamlanmaDurumu == true).GroupBy(p => p.OncelikDurumu).Select(x => new ClassOncelikDurumAnaliz
                {

                    onceliktipi = x.Key,
                    oncelikadeti = x.Count(),
                }).ToList();

            return snf;
        }




        public ActionResult TamamalanmamisOncelikGruplari()
        {
            return View();
        }
        public ActionResult VisualizeTamamlanmayanDurumruplari()
        {
            return Json(OncelikTamamlanmisGrupTİpi(), JsonRequestBehavior.AllowGet);
        }
        public List<ClassOncelikDurumAnaliz> OncelikTamamlanmisGrupTİpi()
        {
            ;
            List<ClassOncelikDurumAnaliz> snf = new List<ClassOncelikDurumAnaliz>();
            using (var c = new ProjeTakipDBContext())

                snf = c.PersonelProjeleris.Where(x => x.TamamlanmaDurumu == false).GroupBy(p => p.OncelikDurumu).Select(x => new ClassOncelikDurumAnaliz
                {

                    onceliktipi = x.Key,
                    oncelikadeti = x.Count(),
                }).ToList();

            return snf;
        }


        public ActionResult GenelProjeRaporlari()
        {
            return View();
        }


        public ActionResult CanliDestek()
        {
            var destek = db.PersonelBilgileris.Where(x => x.Departman == "Yönetim");
            return View(destek.ToList());
        }

    }
}

ProjeTakip/Views/ProjeRaporlari/CanliDestek.cshtml
@model IEnumerable<ProjeTakip.Models.Personel.PersonelBilgileri>
@{
    ViewBag.Title = "CanliDestek";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">
    (function () {
        var options = {
            whatsapp: "905000000000",
            call_to_action: "Destek hattına hoşgeldiniz",
            position: "left",
        };
        var proto = document.location.protocol, host = "getbutton.io", url = proto + "//static." + host;
        var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true; s.src = url + '/widget-send-button/js/init.js';
        s.onload = function () { WhWidgetSendButton.init(host, proto, options); };
        var x = document.getElementsByTagName('script')[0]; x.parentNode.insertBefore(s, x);
    })();
</script>

ProjeTakip/Views/ProjeRaporlari/GenelProjeRaporlari.cshtml
@{
    ViewBag.Title = "GenelProjeRaporlari";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-6">
        @Html.Action("TamamalanmisOncelikGruplari", "ProjeRaporlari")
    </div>
    <div class="col-md-6">

        @Html.Action("TamamalanmamisOncelikGruplari", "ProjeRaporlari")
    </div>
</div>

ProjeTakip/Views/ProjeRaporlari/TamamalanmamisOncelikGruplari.cshtml
@{
    ViewBag.Title = "TamamalanmamisOncelikGruplari";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="col-md-12">

    <div class="card card-info">
        <div class="card-header">
            <h3 class="card-title"><b>TAMAMLANMAMIŞ ÖNCELİK GRUP DAĞILIMI</b></h3>
        </div>

        <!-- /.card-header -->
        <div class="card-body">





            <div id="PieTamamlanmamisOncelikchart_div"></div>



        </div>

    </div>
</div>


<script type="text/javascript" src="https://www.google.com/jsapi"></script>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

<script src="~/Scripts/jquery-3.6.4.js"></script>
<script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizeTamamlanmayanDurumruplari", "ProjeRaporlari")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawTamamlanmamisOncelikChart(result);
                    });
                }
            });
        });
    function drawTamamlanmamisOncelikChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Öncelik');
            data.addColumn('number', 'Proje Adı');
            var dataArray = [];
            $.each(result, function (i, obj) {
                dataArray.push([obj.onceliktipi, obj.oncelikadeti]);
            });
            data.addRows(dataArray);
            var mycolumnChartOptions = {
              /*  title: "Ürün - Stok Grafiği",*/
                width: "100%",
                height: 260,
                pieHole: 0.4,
                bar: { groupWidth: "100%" },
            };
            var mycolumnChart = new google.visualization.PieChart(document
                .getElementById('PieTamamlanmamisOncelikchart_div'));

            mycolumnChart.draw(data, mycolumnChartOptions);
        }
</script>

ProjeTakip/Views/ProjeRaporlari/TamamalanmisOncelikGruplari.cshtml
@{

    ViewBag.Title = "TamamalanmisOncelikGruplari";

    Layout = "~/Views/Shared/_Layout.cshtml";

}



<div class="col-md-12">

    <div class="card card-info">
        <div class="card-header">
            <h3 class="card-title"><b>TAMAMLAŞMIS ÖNCELİK GRUP DAĞILIMI</b></h3>
        </div>

        <!-- /.card-header -->
        <div class="card-body">





            <div id="PieTamamlanmisOncelikchart_div"></div>



        </div>

    </div>
</div>


<script type="text/javascript" src="https://www.google.com/jsapi"></script>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

<script src="~/Scripts/jquery-3.6.4.js"></script>
<script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizeSTamamlanmisDurumGruplari", "ProjeRaporlari")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        PieTamamlanmisOncelikchart(result);
                    });
                }
            });
        });
    function drawPieTamamlanmisOncelikChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Öncelik');
            data.addColumn('number', 'Proje Adı');
            var dataArray = [];
            $.each(result, function (i, obj) {
                dataArray.push([obj.onceliktipi, obj.oncelikadeti]);
            });
            data.addRows(dataArray);
            var mycolumnChartOptions = {
              /*  title: "Ürün - Stok Grafiği",*/
                width: "100%",
                height: 260,
                pieHole: 0.4,
                bar: { groupWidth: "100%" },
            };
            var mycolumnChart = new google.visualization.PieChart(document
                .getElementById('PieTamamlamisOncelikchart_div'));

            mycolumnChart.draw(data, mycolumnChartOptions);
        }
</script>